apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: my-app
        image: 124355666784.dkr.ecr.ap-northeast-2.amazonaws.com/peerjs-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"
        - name: HTTPS
          value: "true"
        volumeMounts:
        - name: static-files
          mountPath: /app/public
      volumes:
      - name: static-files
        configMap:
          name: static-files
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 9000
  selector:
    app: my-app