apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2                # Number of pods
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 124355666784.dkr.ecr.ap-northeast-2.amazonaws.com/my-app:latest  # Your ECR image
        ports:
        - containerPort: 80   # Must match EXPOSE in Dockerfile
      imagePullSecrets:       # Only needed if you had auth issues
        - name: ecr-secret    # Use the secret created earlier