# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]  # Changed from "master" to "main"
  pull_request:
    branches: ["main"]  # Changed from "master" to "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]  # Test across Node.js versions 16, 18, and 20
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"  # Cache npm dependencies to speed up builds

      - name: Install dependencies
        run: npm ci  # Clean install dependencies

      - name: Build the project
        run: npm run build  # Run the build script

      - name: Run linting
        run: npm run lint  # Run linting to check code style

      - name: Run tests and generate coverage
        run: npm run coverage  # Run tests and generate coverage report